CREATE TABLE job_history
  (
    JOB_HISTORY_ID bigserial NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NULL,
    JOB_NAME VARCHAR(200) NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    STATUS VARCHAR(10) NULL,
    MESSAGE VARCHAR(200) NULL,
    PRIMARY KEY (JOB_HISTORY_ID)
);

CREATE UNIQUE INDEX IDX_JOB_HISTORY_ID ON JOB_HISTORY(JOB_HISTORY_ID);
CREATE INDEX IDX_JOB_HISTORY_START_TIME ON JOB_HISTORY(START_TIME DESC);
CREATE INDEX IDX_JOB_HISTORY_END_TIME ON JOB_HISTORY(END_TIME DESC);
CREATE INDEX IDX_JOB_HISTORY_START_END_TIME ON JOB_HISTORY(START_TIME DESC, END_TIME DESC);
CREATE INDEX IDX_JOB_HISTORY_JOB_NAME ON JOB_HISTORY(JOB_NAME);